version: '3.7'
services:
    db:
        container_name: db
        image: mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3306:3306"
        volumes:
            - mysql_volume:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        networks:
            - db


    php:
        container_name: php-fpm
        build: ./php-fpm
        ports:
            - "9000:9001"
        volumes:
            - ./symfony-app:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
        depends_on: 
            - db
        networks:
            - db
            - php


    nginx:
        container_name: nginx
        build: ./nginx
        ports:
            - "80:80"
        depends_on: 
            - php
        networks:
            - php
            - phpmyadmin
        volumes:
            - ./logs/nginx:/var/log/nginx:cached
            - ./symfony-app:/var/www/symfony:cached


    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            PMA_HOST: db
            PMA_ABSOLUTE_URI: "http://dbadmin.localhost"
        ports:
            - "8080:80"
        depends_on: 
            - db
        networks: 
            - db
            - phpmyadmin


networks:
    db:
    php:
    phpmyadmin:

    
volumes: 
    mysql_volume:
        external: true